### PR TITLE
Add domob's signature.

### PR DESCRIPTION
**Pull request by domob1812**

### CODE REVIEW

**Comment by JeremyRand** [comment]
Any chance you could change this to ASCII-armored format?  (Reasons are consistency with the other sigs, and improved UX for people copying/pasting the sigs from GitHub's web UI.)

**Comment by domob1812** [comment]
Sure, changed.  (I've typically seen `.asc` used for ASCII format and `.sig` for binary, that's why I assumed you did binary signatures, too.)

**Comment by JeremyRand** [comment]
Hmm, good point.  The Qubes repo appears to use ASCII-armored signatures with `.sig`, which is why I did it that way, but if you think it's less ambiguous I'm okay with pushing a commit that renames the `.sig` files to `.asc`.  Should I do that?

**Comment by domob1812** [comment]
That's up to you.  I would find it more consistent to have the files named with `.asc`, but I can verify them fine with `gpg2` either way, so it should not really matter.

**Comment by JeremyRand** [comment]
Renamed to `.asc`.

**Pull request merged**
